name: Notifications MQTT
color: null
values:
  - key: mqttBrokerUrl
    value: mqtt://broker.hivemq.com:1883
    enabled: true
  - key: mqttTopic
    value: postman-api-catalog-demo/notifications
    enabled: true
