name: Production Refund Webhook
values:
  - key: baseUrl
    value: https://7ygtn6bgtcbmv8k2oigij4xc0.webhook.pstmn.io
    enabled: true
createdAt: 2026-07-07T00:00:00.000Z
updatedAt: 2026-07-07T00:00:00.000Z
