name: Production Payments AWS
color: null
values:
  - key: baseUrl
    value: https://18-157-170-15.nip.io
    enabled: true
  - key: refundWebhookUrl
    value: https://7ygtn6bgtcbmv8k2oigij4xc0.webhook.pstmn.io/
    enabled: true
