owner: "53522859"
team: "14577123"
lastUpdatedBy: "53522859"
lastRevision: 1783496467000
name: Production Refund Webhook
color: null
values:
  - key: baseUrl
    value: https://7ygtn6bgtcbmv8k2oigij4xc0.webhook.pstmn.io
    enabled: true
createdAt: 2026-07-08T07:41:07.000Z
updatedAt: 2026-07-08T07:41:07.000Z
