// Postman Application Configuration
// Generated by `postman application init`
//
// Docs: https://learning.postman.com/docs/postman-cli/postman-cli-options/

module.exports = {
    // The command to run before analysis (e.g. your test suite).
    command: 'npm run test:ui',

    // Targets define which collections and environment to use for analysis.
    // Select a target at runtime with: postman application test --target <name>
    targets: {
        default: {
            environment: 'Production Orders',
            // Referenced by name. UID for reference / disambiguation:
            // 53522859-54ec8184-2939-4cef-8528-56e1936bbae5
            collections: [
                'Orders - QA'
            ],
        },

        // Example: a beta/staging target
        // beta: {
        //     environment: 'Staging',
        //     collections: [
        //         'My Collection',
        //     ],
        // },

        // Example: a production target
        // production: {
        //     environment: 'Production',
        //     collections: [
        //         'My Collection',
        //     ],
        // },
    },

    // Drop non-API noise so the dashboard shows only real Orders API traffic:
    // the app's own assets/HMR served from localhost, and CORS preflights.
    // (API calls go to *.workers.dev, so filtering localhost is safe.)
    filters: {
        urlPatterns: ['localhost:5173'],
        methods: ['OPTIONS'],
        headers: {},
    },

    // Filters exclude matching network requests from analysis.
    // A request is dropped if it matches any rule below.
    //
    // `filters` can also be an array of scoped entries. Each entry may add
    // `target` (regex on the test path) and/or `tags` (Playwright tags) so the
    // rule only applies to matching tests; a request is dropped if any entry
    // catches it (tags are honored on the native withPostman path only):
    //   filters: [
    //     { target: 'monitors/.*\\.spec\\.ts', urlPatterns: ['/sentry'] },
    //     { tags: ['@smoke'], methods: ['OPTIONS'] },
    //     { urlPatterns: ['/health'] }, // global fallback, applies everywhere
    //   ],
    // filters: {
    //     urlPatterns: ['\\.css$', '\\.svg$', 'analytics\\.example\\.com'],
    //     methods: [],
    //     headers: {},
    // },

    // Transformers rewrite proxied requests back to their real upstream URLs
    // so that captured traffic can be matched against your Postman collections.
    //
    // When your app routes API calls through a gateway or proxy, the captured
    // URL is the gateway URL — not the real service URL. Each transformer entry
    // lets you reverse that mapping:
    //
    //   url              – prefix string or RegExp to match the transformer URL.
    //   transformRequest  – receives the raw request body and a context
    //                       ({ url, method, requestHeaders }) describing the
    //                       captured request, and returns { url, method }
    //                       pointing to the real service.
    //   transformResponse – (optional) unwraps the transformer response envelope
    //                       so assertions see the real payload.
    //
    // transformers: [
    //     {
    //         url: 'https://api-gateway.example.com',
    //
    //         transformRequest (body, ctx) {
    //             // Rewrite the gateway host to the real upstream while
    //             // preserving the captured path/query. Resolve the target
    //             // service from a routing header when present.
    //             var service = (ctx.requestHeaders || {})['x-service'];
    //             var host = service
    //                 ? service + '.internal.example.com'
    //                 : 'api.internal.example.com';
    //
    //             return {
    //                 url: ctx.url.replace('api-gateway.example.com', host),
    //                 method: ctx.method,
    //             };
    //         },
    //
    //         transformResponse (response) {
    //             if (response && typeof response === 'object' && 'data' in response) {
    //                 return response.data;
    //             }
    //
    //             return response;
    //         },
    //     },
    // ],
};
