$kind: http-example
request:
  url: "{{baseUrl}}/openapi.json"
  method: GET
  headers:
    Accept: application/json
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "openapi": "3.0.3",
        "info": {
          "title": "Orders API",
          "version": "1.0.0",
          "description": "string"
        },
        "paths": {
          "key_0": 5307.161398901075
        },
        "servers": [
          {
            "url": "https://NgPT.fzcCurK-lGXw9LtddJDIjQWlu2K3MymVOK-EOKBfXzCmL-d",
            "description": "string"
          },
          {
            "url": "http://hfTlVzNTsnMPsWNOSfVcJhHwJ.qtxQWxWX.vlmgjMrfAcZRDL18RqLVQ3S5z+9F",
            "description": "string"
          }
        ],
        "components": {
          "key_0": "string"
        }
      }
order: 1000
