id: 01a0c81a-ed81-7347-bb79-b3b039acec9e
version: 1
name: Orders API Mock
slug: new-mock-02314
enableSession: true
protocol: http
port: 4500
autoRestartOnChange: true
logging:
  level: verbose
  showBody: true
scenarios:
  - name: default
    path: ./default.js
    default: true
