$kind: http-request
description: ""
url: "{{baseUrl}}/openapi.json"
method: GET
headers:
  Accept: application/json
body:
  type: text
  content: ""
settings: {}
examples: ./.resources/OpenAPI specification.resources/examples
order: 1000
